Implement mergeSort() function
Al2Klimov/trainee-php-sort pull request #24
Opened 2020-05-15 15:05 UTC by Yonas-net

resoves #12

2020-05-15 15:27 UTC, Al2Klimov requested changes

2020-05-15 15:27 UTC, Al2Klimov commented on sort.php
> +    while ($funcCallback(0, sizeof($leftSide)) && $funcCallback(0, sizeof($rightSide))) {
Why are you using $funcCallback for values not from your input?

2020-05-15 15:27 UTC, Al2Klimov commented on sort.php
> +    while ($funcCallback(0, sizeof($leftSide))) {
Same here.

2020-05-15 15:27 UTC, Al2Klimov commented on sort.php
> +    while ($funcCallback(0, sizeof($rightSide))) {
And here.

2020-05-15 15:35 UTC, Al2Klimov requested changes

2020-05-15 15:35 UTC, Al2Klimov commented on sort.php
> +    }
Any way to shorten this, maybe to a one-liner?

2020-05-15 15:41 UTC, Al2Klimov commented on sort.php
> +    }
I meant the whole while.

2020-05-18 08:46 UTC, Al2Klimov requested changes
* [ ] `git reset --soft HEAD~$(git rev-list --count $(git merge-base HEAD master)..HEAD^)`
* [ ] `git commit --amend --no-edit`
* [ ] `git push -f origin feature/sort-#12`

2020-05-18 09:12 UTC, Yonas-net commented
##Testprotocol #12

Test protocol for ``--mergesort`` parameter.

The content of the in.txt file looks like this.
```
13
8
12
6
2
10
1
7
0
```
Commands with the ``--mergesort`` and ``--numeric-sort`` parameter.
``php sort.php --mergesort -n in.txt`` AND ``php sort.php --mergesort -n < in.txt``  output:
```
0                                             0
1                                             1
2                                             2
6                                             6
7                                             7
8                                             8
10                                            10
12                                            12
13                                            13
```
and without ``--numeric-sort`` parameter the output looks like this..
``php sort.php --mergesort in.txt`` AND ``php sort.php --mergesort < in.txt``
```
0                                       0
1                                       1
10                                      10
12                                      12
13                                      13
2                                       2
6                                       6
7                                       7
8                                       8
```

See you next time!

:+1:

2020-05-18 09:19 UTC, Al2Klimov approved these changes

2020-05-18 09:19 UTC, merged